name: one-click-multisite
type: wordpress
docroot: .ddev/wordpress
php_version: "8.1"
nodejs_version: "22"
webserver_type: nginx-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "11.8"
use_dns_when_possible: true
composer_version: "2"
hooks:
    post-start:
        - exec: .ddev/commands/setup.sh
web_environment:
    - WP_TITLE=One Click Multisite
    - ADMIN_USER=admin
    - ADMIN_PASS=admin
corepack_enable: false
upload_dirs:
    - wp-content/uploads
